### ISSUE TITLE
Specifying just the IP/Hostname to dirbust causes a segfault

### ISSUE THREAD

**Issue by jack-the-r1pper** [phra/rustbuster#13]
Doing `rustbuster --url 127.0.0.1 --wordlist /usr/share/dirb/wordlists/common.txt`
should produce the same output as
 `rustbuster --url 127.0.0.1/ --wordlist /usr/share/dirb/wordlists/common.txt` 
but the latter gives a segmentation fault on 
`Linux htb 4.19.0-kali5-amd64 #1 SMP Debian 4.19.37-2kali1 (2019-05-15) x86_64 GNU/Linux`

Image:
![image](https://user-images.githubusercontent.com/24259204/58430952-92a7b600-80a3-11e9-95d7-57bfa1baedaf.png)

**Comment by phra** [comment]
v1.2.1 was released to address the issue. thanks.

https://github.com/phra/rustbuster/releases/tag/v1.2.1
