### ISSUE TITLE
Wordlist read error

### ISSUE THREAD

**Issue by xaeroborg** [phra/rustbuster#26]
I am getting this error with any .txt that I run along with a dir bust
![image](https://user-images.githubusercontent.com/33274680/61069858-72f00580-a437-11e9-83b2-80cf46d9af2c.png)

**Comment by phra** [comment]
I received similar reports outside GitHub but as you can see from the error Rustbuster only supports UTF-8 encoded text files.

For more information, check also this: https://github.com/danielmiessler/SecLists/pull/298

**Comment by xaeroborg** [comment]
> 
> 
> I received similar reports outside GitHub but as you can see from the error Rustbuster only supports UTF-8 encoded text files.
> 
> For more information, check also this: [danielmiessler/SecLists#298](https://github.com/danielmiessler/SecLists/pull/298)

Thanks for referencing this to me. Now I am able to run rustbuster with the UTF-8 encoded text files. Its insanely fast. Great work.
