### ISSUE TITLE
dns flag '-u' error

### ISSUE THREAD

**Issue by xaeroborg** [phra/rustbuster#27]
As its mentioned in the example usage, I used a '-u' along with dns bust but its giving out an error
![image](https://user-images.githubusercontent.com/33274680/61070321-9798ad00-a438-11e9-817e-88259d1fa227.png)

**Comment by phra** [comment]
aaarrr, silly typo, it should be `-d`. i am going to update the usage text.

`rustbuster dns -d google.com -w /usr/share/seclists/Discovery/DNS/subdomains-top1mil-5000.txt`

**Comment by phra** [comment]
https://github.com/phra/rustbuster/releases/tag/v3.0.2 was released to address this issue.
